### ISSUE TITLE
Why not in common role ?

### ISSUE THREAD

**Issue by bewiwi** [henyxia/ansible#5]
You install python here for every host, why not in the common role ?https://github.com/henyxia/ansible/blob/d7028fe91ca1971e4308eaf6304cdca1e4304ebe/site.yml#L9

**Comment by henyxia** [comment]
This part is separated because it requires to disable fact gathering (https://github.com/henyxia/ansible/blob/d7028fe91ca1971e4308eaf6304cdca1e4304ebe/site.yml#L4) and the common role needs it.
